name: topperstation
recipe: pantheon
config:
  framework: drupal8
  site: topperstation
  id: db5fb5e4-3225-46f0-b0a9-1cc803600c48

services:
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database