ignored_config_entities:
  0: brightcove.brightcove_api_client.brightcove_west_liberty_university
  2: page_manager.page_variant.home-panels_variant-0
  4: page_manager.page_variant.node_view-panels_variant-1
  6: page_manager.page_variant.player-panels_variant-0
  8: page_manager.page_variant.schedule-panels_variant-0
  10: page_manager.page_variant.search-panels_variant-0
  12: page_manager.page_variant.shows-panels_variant-0
  14: block.block.mainnavigation_2
  16: block.block.socialmedialinks
  18: system.performance
  20: simple_block.simple_block.schedule_intro
  22: simple_block.simple_block.watch_videos_intro
_core:
  default_config_hash: UVH1aJ4b44UM-VdPVN7hNNuuVqfReJxwfVeDQH1Hvsk
