module:
  addtoany: 0
  admin_toolbar: 0
  automated_cron: 0
  better_exposed_filters: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_content: 0
  block_content_permissions: 0
  breakpoint: 0
  brightcove: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_direct_save: 0
  config_filter: 0
  config_ignore: 0
  contextual: 0
  crop: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_browser: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  focal_point: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  kint: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_block: 0
  menu_reference_render: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  module_filter: 0
  node: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panels: 0
  panels_ipe: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search_api: 0
  search_api_db: 0
  shortcut: 0
  simple_block: 0
  slick: 0
  slick_entityreference: 0
  slick_ui: 0
  slick_views: 0
  smart_trim: 0
  social_link_field: 0
  social_link_field_ts: 0
  social_media_links: 0
  statistics: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  text: 0
  time_field: 0
  time_formatter: 0
  token: 0
  toolbar: 0
  tour: 0
  ts_social_media_links: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_jump_menu: 0
  views_selective_filters: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  topperstation: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
